package:
    name: quantities
    version: "0.11.0"

source:
    fn: quantities-0.11.0.zip
    url: https://pypi.python.org/packages/source/q/quantities/quantities-0.11.0.zip
    md5: e966afe6c77e7e1d3a6e3f726cb59dc1

build:
    number: 0

requirements:
    build:
      - python
      - numpy
    run:
      - python
      - numpy

test:
    imports:
      - quantities
      - quantities.constants
      - quantities.tests
      - quantities.units

about:
    home: http://pythonhosted.org//quantities/
    license: BSD
    summary: 'Physical quantities with units, based upon Numpy'
