package:
  name: fiona
  version: 1.6.2.dev1

source:
  git_tag: master
  git_url: https://github.com/Toblerity/Fiona

build:
  number: 0
  skip: True # [win]

requirements:
  build:
    - python
    - six
    - numpy
    - gdal
    - cligj
    - cython
    - munch
    - click-plugins

  run:
    - python
    - six
    - numpy
    - gdal
    - cligj
    - munch
    - click-plugins

test:
  imports:
    - fiona

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD License
  summary: Fiona is OGR's neat, nimble, no-nonsense API for Python programmers.
