package:
  name: libspatialindex
  version: 1.8.5

source:
  git_url: https://github.com/libspatialindex/libspatialindex.git
  git_tag: 1.8.5

build:
  number: 0

about:
  home: http://libspatialindex.github.io
  summary: 'extensible framework for robust spatial indexing'
