package:
    name: freezegun
    version: "0.3.5"

source:
    fn: freezegun-0.3.5.tar.gz
    url: https://pypi.python.org/packages/source/f/freezegun/freezegun-0.3.5.tar.gz
    md5: 47065c66612f65b1cc2b8659970ee99a

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - six
        - python-dateutil >=1.0,!=2.0
    run:
        - python
        - six
        - python-dateutil >=1.0,!=2.0

test:
    imports:
        - freezegun

about:
    home: https://github.com/spulec/freezegun
    license: Apache-2.0
    summary: 'Let your Python tests travel through time'
