package:
    name: pyresample
    version: "1.1.4"

source:
    fn: pyresample-1.1.4.tar.gz
    url: https://pypi.python.org/packages/source/p/pyresample/pyresample-1.1.4.tar.gz
    md5: 57900c8d290ea61cd4af7954274d9bba

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - scipy
        - pyproj
        - numpy
        - configobj
        - pykdtree  # [not win]
        - numexpr

test:
    imports:
        - pyresample

about:
  home: https://github.com/mraspaud/pyresample/
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Resampling of remote sensing data in Python'
