package:
  name: mplexporter
  version: !!str 0.0.1

source:
  #fn: mplexporter-0.0.1.tar.gz
  git_url: https://github.com/ocefpaf/mplexporter.git
  git_branch: fix_url

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib

test:
  # Python imports
  imports:
    - mplexporter

about:
  home: https://github.com/mpld3/mplexporter
  license: BSD 3-clause
  summary: 'General Matplotlib Exporter'
