package:
  name: pygridgen
  version: !!str 0.1

source:
  git_url: https://github.com/phobson/pygridgen.git
  git_tag: develop

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - basemap
    - numpy
    - nose

  run:
    - python
    - pandas
    - numpy
    - matplotlib
    - basemap
    - nose

test:
  # Python imports
  imports:
    - pygridgen

  commands:
    - nosetests
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
   - nose

about:
  home: https://github.com/hetland/pygridgen.git
  license:  BSD License
  summary: 'Python interface to gridgen by Pavel Sakov'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
