package:
    name: pygridgen
    version: "0.1"

source:
    git_url: https://github.com/phobson/pygridgen.git
    git_tag: develop

build:
    number: 2

requirements:
    build:
        - python >=2.7,<3
        - numpy
    run:
        - python
        - pandas
        - numpy
        - matplotlib
        - basemap
        - csa
        - gridgen
        - gridutils
        - nn

test:
    imports:
        - pygridgen

about:
    home: https://github.com/hetland/pygridgen.git
    license:  BSD License
    summary: 'Python interface to gridgen by Pavel Sakov'
