
package:
  name: pygridgen
  version: !!str 0.1

source:
  git_url: https://github.com/phobson/pygridgen.git
  git_tag: new-paths
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - seaborn = seaborn:main
    #
    # Would create an entry point called seaborn that calls seaborn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - basemap
    - numpy
    - nose

  run:
    - python
    - pandas
    - numpy
    - matplotlib
    - basemap 
    - nose

test:
  # Python imports
  imports:
    - pygridgen

  commands:
    - nosetests
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
   - nose

about:
  home: https://github.com/hetland/pygridgen.git
  license:  BSD License
  summary: 'Python interface to gridgen by Pavel Sakov'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
