package:
    name: folium
    version: "0.2.0"

source:
    git_url: https://github.com/ocefpaf/folium.git
    git_tag: simple_gjstyle

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - numpy
        - pandas
        - vincent

test:
    imports:
        - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
