package:
  name: folium
  version: !!str 0.1.3

source:
  fn: folium-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/f/folium/folium-0.1.3.tar.gz
  md5: c8db7e684a69a7e9c714fcac93859a9f

build:
  number: 0

requirements:
  build:
    - python
    #- setuptools

  run:
    - python
    #- setuptools
    - jinja2
    # Optional.
    #- openpyxl 1.8.5
    #- pandas

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
