package:
  name: folium
  version: !!str ${VERSION}

source:
  git_url: https://github.com/ocefpaf/folium.git
  git_branch: MANIFEST

build:
  number: 0

requirements:
  build:
    - python
  run:
    - jinja2
    - numpy
    - pandas

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js & Python'
