package:
  name: folium
  version: !!str ${VERSION}

source:
  git_url: https://github.com/wrobstory/folium.git

requirements:
  build:
    - python
  run:
    - jinja2
    - pandas

test:
  requires:
    - nose
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js & Python'
