package:
    name: folium
    version: "0.1.5"

source:
    fn: folium-0.1.5.tar.gz
    url: https://pypi.python.org/packages/source/f/folium/folium-0.1.5.tar.gz
    md5: 64bfb417ce53638a3f57245bcaf38215

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2

test:
    imports:
        - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
