package:
    name: folium
    version: "0.1.6"

source:
    fn: folium-0.1.6.tar.gz
    url: https://pypi.python.org/packages/source/f/folium/folium-0.1.6.tar.gz
    md5: 96e76012d2517a376f2805a4860f8d1e

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - numpy
        - pandas
        - vincent

test:
    imports:
        - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
