package:
    name: folium
    version: "0.1.5"

source:
    git_url: https://github.com/python-visualization/folium.git
    git_branch: 65c6a3db9f84fee66b834bd8cbfe92ca0ef9f9dd

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2

test:
    imports:
        - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
