package:
    name: mingwpy
    version: "0.1.0"

source:
    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp34-none-win32.whl     # [py34 and win32]
    fn: mingwpy-0.1.0b3-cp34-none-win32.whl                                                           # [py34 and win32]
    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp34-none-win_amd64.whl # [py34 and win64]
    fn: mingwpy-0.1.0b3-cp34-none-win_amd64.whl                                                       # [py34 and win64]
    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp27-none-win32.whl     # [py27 and win32]
    fn: mingwpy-0.1.0b3-cp27-none-win32.whl                                                           # [py27 and win32]
    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp27-none-win_amd64.whl # [py27 and win64]
    fn: mingwpy-0.1.0b3-cp27-none-win_amd64.whl                                                       # [py27 and win64]

build:
    number: 0  # [win]

requirements:
    run:
        - python  # [win]
    build:
        - python  # [win]
        - setuptools  # [win]

about:
    home: https://github.com/mingwpy/mingw-builds
    license: 3-clause BSD
    summary: 'GCC for Windows 64 & 32 bits'
