package:
  name: iris
  version: 1.6.0
source:
  url: git@github.com:/esc24/iris/archive/udunits_xml_path.tar.gz
  md5: ad25bc09e4f86c69f596da69845e0c36ad25bc09e4f86c69f596da69845e0c36 

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy   
    - udunits2
    - netcdf4
    - pyke
    - cartopy   
    - nose
    - setuptools
  run:
    - python
    - numpy
    - scipy   
    - udunits2
    - netcdf4
    - pyke
    - cartopy   
    - shapely
    - matplotlib

test:
  imports:

about:
  home: http://scitools.org.uk/iris
  license: Open Government License (UK)
