language: c

os:
    - osx

sudo: false

env:
    global:
        secure: "fVnEwIDKsEr20f6iVe63Gg/v0ewQf/VAFKnMneSDU7dH9T0V95Eylp6LbpVRahpvjFzcYFPrPGsjtqCrYaeDhCxzkU7gsw//l11hq12IY76lmDZuIryr3Z8CIyqYIEnvqrXdRtM/1RAkvldY6Tj72e3+K+WCnBOfCZ8Cv76pbJc="

addons:
    apt:
        packages:
            # UDUNITS2
            - texinfo
            # libmo_unpack
            - check
            # NCO
            - gfortran
            - antlr
            - g++
            - bison
            - flex
            - libantlr-dev
            - gsl-bin
            - libgsl0-dev

before_install:
    - brew update
    # Unit testing framework for C (used by libmo_unpack).
    - brew install check
    # NCO.
    - brew outdated gcc || brew upgrade gcc
    - brew install gsl
    # https://travis-ci.org/ioos/conda-recipes/builds/67641190
    #- brew install antlr2

install:
    # Download and run bootstrap.
    - wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
    - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
    - conda config --set show_channel_urls True
    - conda install -c http://conda.binstar.org/pelson/channel/development --yes --quiet obvious-ci
    - conda config --add channels ioos
    - obvci_install_conda_build_tools.py

script:
    - obvci_conda_build_dir.py ./ ioos --channel main --build-condition "python >=2.7,<3|==3.4"
