language: objective-c  # MacOS builds.

env:
    global:
        secure: "fVnEwIDKsEr20f6iVe63Gg/v0ewQf/VAFKnMneSDU7dH9T0V95Eylp6LbpVRahpvjFzcYFPrPGsjtqCrYaeDhCxzkU7gsw//l11hq12IY76lmDZuIryr3Z8CIyqYIEnvqrXdRtM/1RAkvldY6Tj72e3+K+WCnBOfCZ8Cv76pbJc="

    matrix:
        - CONDA_PY=27  CONDA_NPY=19

before_install:
    - brew update
    # NCO.
    - brew outdated gcc || brew upgrade gcc
    - brew install gsl
    # https://travis-ci.org/ioos/conda-recipes/builds/67641190
    #- brew install antlr2

install:
    # Download and run bootstrap.
    - wget https://raw.githubusercontent.com/pelson/Obvious-CI/v0.3.0/bootstrap-obvious-ci-and-miniconda.py
    - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
    # Config conda channels.
    - conda config --set show_channel_urls True
    - conda config --add channels http://conda.binstar.org/ioos
    # Install Obvious-CI.
    - conda install -c http://conda.binstar.org/ioos/channel/main --yes --quiet obvious-ci
    - obvci_install_conda_build_tools.py

script:
    - obvci_conda_build_dir.py ./ ioos --channel main
