language: c

os:
 - linux
 - osx

env:
    global:
        secure: "fVnEwIDKsEr20f6iVe63Gg/v0ewQf/VAFKnMneSDU7dH9T0V95Eylp6LbpVRahpvjFzcYFPrPGsjtqCrYaeDhCxzkU7gsw//l11hq12IY76lmDZuIryr3Z8CIyqYIEnvqrXdRtM/1RAkvldY6Tj72e3+K+WCnBOfCZ8Cv76pbJc="

    matrix:
        - CONDA_PY=27  CONDA_NPY=19

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gfortran

install:
    # Install makeinfo - needed for constructing configuration files via autoreconf (in particular for udunits).
    - if [[ "$OSTYPE" == "linux-gnu" ]]; then sudo apt-get install texinfo; fi

    - wget https://raw.githubusercontent.com/pelson/Obvious-CI/v0.1.0/bootstrap-obvious-ci-and-miniconda.py
    - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
    - conda config --set show_channel_urls True && conda config --add channels http://conda.binstar.org/ioos/channel/main
    # NOTE: I am going to keep this for now.  We probably need something from his latest obvious-ci version.
    - conda install -c http://conda.binstar.org/pelson/channel/development --yes --quiet obvious-ci
    - conda config --add channels http://conda.binstar.org/ioos
    - obvci_install_conda_build_tools.py

script:
    - obvci_conda_build_dir.py ./ ioos --channel main
