package:
  name: rdflib
  version: 4.0.1

source:
  fn: rdflib-4.0.1.tar.gz
  url: https://pypi.python.org/packages/source/r/rdflib/rdflib-4.0.1.tar.gz
  md5: c8491ec57dfc146b388398bef550ec79
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rdflib = rdflib:main
    #
    # Would create an entry point called rdflib that calls rdflib.main()

    - rdfpipe = rdflib.tools.rdfpipe:main
    - csv2rdf = rdflib.tools.csv2rdf:main
    - rdf2dot = rdflib.tools.rdf2dot:main
    - rdfs2dot = rdflib.tools.rdfs2dot:main
    - rdfgraphisomorpishm = rdflib.tools.graphisomorphism:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - isodate
    - pyparsing
#    - SPARQLWrapper
    - html5lib

  run:
    - python
    - distribute
    - isodate
    - pyparsing
#   - SPARQLWrapper
    - html5lib

test:
  # Python imports
  imports:
    - rdflib

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - rdfpipe --help
#    - csv2rdf --help
#    - rdf2dot --help
#    - rdfs2dot --help
#    - rdfgraphisomorpishm --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD License
  summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

