package:
  name: scp
  version: !!str 0.8.0

source:
  fn: scp-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/s/scp/scp-0.8.0.tar.gz
  md5: 7240f8717a8ba8abc1b935e16d4bd992
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scp = scp:main
    #
    # Would create an entry point called scp that calls scp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paramiko

  run:
    - python
    - paramiko

test:
  # Python imports
  imports:
    - scp

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL
  summary: 'scp module for paramiko'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
