package:
  name: folium
  version: !!str 0.1.2_dev_f7194ad

source:
  git_url: https://github.com/ocefpaf/folium.git
  git_branch: MANIFEST

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - jinja2
    - numpy
    - openpyxl 1.8.5
    - pandas
    - python
    - setuptools
    - nose

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js & Python'
