package:
  name: pyoos
  version: !!str 0.6.0

source:
  fn: pyoos-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyoos/pyoos-0.6.0.tar.gz
  md5: e62f7d990a5fe3ff453c519ca6a748c2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyoos = pyoos:main
    #
    # Would create an entry point called pyoos that calls pyoos.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paegan
    - owslib
    - requests
    - fiona
    - beautifulsoup4
    - lxml
    - pytest

  run:
    - python
    - paegan
    - owslib
    - requests
    - fiona
    - beautifulsoup4
    - lxml
    - pytest

test:
  # Python imports
  imports:
    - tests
    - pyoos.parsers
    - pyoos.collectors.nerrs
    - pyoos.collectors
    - pyoos
    - pyoos.collectors.hads
    - pyoos.collectors.coops
    - pyoos.collectors.ndbc
    - pyoos.parsers.ioos
    - pyoos.collectors.usgs
    - pyoos.collectors.ioos
    - pyoos.parsers.ioos.one
    - pyoos.parsers.wqx
    - pyoos.utils
    - pyoos.collectors.awc
    - pyoos.collectors.wqp
#   - tests.collectors

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/asascience-open/pyoos
  license: GNU General Public License v3 (GPLv3)
  summary: 'A Python library for collecting Met/Ocean observations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
