package:
    name: fortran-magic
    version: "0.5.1"

source:
    fn: fortran-magic-0.5.1.tar.gz
    url: https://pypi.python.org/packages/source/f/fortran-magic/fortran-magic-0.5.1.tar.gz
    md5: dfcd7d23b0608537722059e3ff885513

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - ipython
        - numpy
    run:
        - python
        - numpy
        - ipython

test:
    imports:
        - fortranmagic

about:
    home: https://github.com/mgaitan/fortran_magic
    license: BSD
    summary: 'IPython extension that help to use Fortran in the interactive session.'
