package:
    name: rasterio
    version: "0.21"

source:
    fn: rasterio-0.21.0.tar.gz
    url: https://pypi.python.org/packages/source/r/rasterio/rasterio-0.21.0.tar.gz
    md5: a3b32d218b28624af4f3aabab647a915

build:
    number: 0

    entry_points:
        - rio = rasterio.rio.main:cli

requirements:
    build:
        - python
        - numpy >=1.8
        - cython >=0.20
        - gdal
        - setuptools
    run:
        - python
        - affine >=1.0
        - cligj
        - enum34
        - numpy >=1.8
        - snuggs >=1.2
        - cython >=0.20
        - gdal

test:
    imports:
        - rasterio

about:
    home: https://github.com/mapbox/rasterio
    license: BSD
    summary: 'Rasterio reads and writes geospatial raster datasets'
