package:
    name: wicken
    version: "0.1.2"

source:
    fn: Wicken-0.1.2.tar.gz
    url: https://pypi.python.org/packages/source/W/Wicken/Wicken-0.1.2.tar.gz
    md5: b522b3e713a8dd90d11c2dbc1cdd44c9

build:
    number: 1

requirements:
    build:
        - python <3
        - setuptools
        - nose >=1.2.0
        - lxml >=3.2.1
        - petulant-bear >=0.1.2
    run:
        - python
        - nose >=1.2.0
        - lxml >=3.2.1
        - petulant-bear >=0.1.2

test:
    imports:
        - wicken

about:
    home: https://github.com/ioos/wicken
    license:  Apache 2.0
    summary: 'Maps metadata concepts to concrete specifications and file formats'
