package:
    name: metakernel
    version: "0.11.3"

source:
    fn: metakernel-0.11.3.tar.gz
    url: https://pypi.python.org/packages/source/m/metakernel/metakernel-0.11.3.tar.gz
    md5: ad48873e3debc2c8651efff9b6519428

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - ipython >=3.0
    run:
        - python
        - ipython >=3.0

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD License
    summary: 'Metakernel for Jupyter'
