package:
    name: metakernel
    version: "0.11.8"

source:
    fn: metakernel-0.11.8.tar.gz
    url: https://pypi.python.org/packages/source/m/metakernel/metakernel-0.11.8.tar.gz
    md5: 8e4082943d38b2c8a516af8b5285bf01

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - ipython >=3.0
    run:
        - python
        - ipython >=3.0

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD License
    summary: 'Metakernel for Jupyter'
