package:
   name: rdflib
   version: "4.1.2"

source:
   fn: rdflib-4.1.2.tar.gz
   url: https://pypi.python.org/packages/source/r/rdflib/rdflib-4.1.2.tar.gz
   md5: a356cf3bdfe1a72d240d151ce5662b84


build:
   entry_points:
   - rdfpipe = rdflib.tools.rdfpipe:main
   - csv2rdf = rdflib.tools.csv2rdf:main
   - rdf2dot = rdflib.tools.rdf2dot:main
   - rdfs2dot = rdflib.tools.rdfs2dot:main
   - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main

requirements:
  build:
   - python
   - setuptools
   - isodate
   - pyparsing
   # - sparqlwrapper # Added via build.sh to avoid circular dependency.
   - html5lib
   - six

  run:
   - python
   - setuptools
   - isodate
   - pyparsing
   # - sparqlwrapper
   - html5lib
   - six

test:
   # Python imports NOTE: Cannot test installation without sparqlwrapper!
   # imports:
   # - rdflib
   # - rdflib.namespace

   commands:
   # You can put test commands to be run here. Use this to test that the
   # entry points work.
   - rdfpipe --help
   # You can also put a file called run_test.py in the recipe that will be run
   # at test time.
   # requires:
   # Put any additional test requirements here. For example
   # - nose

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD License
  summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information'

