package:
  name: utilities
  version: "0.2.1"

source:
  git_url: https://github.com/pyoceans/utilities.git
  git_tag: v0.2.1

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - iris
    - lxml
    - pandas
    - beautifulsoup4

  run:
    - python
    - iris
    - lxml
    - pandas
    - beautifulsoup4
    - folium
    - ipython-notebook
    - oceans
    - pyugrid  # [not win]

test:
  imports:
    - utilities

about:
  home: https://github.com/ocefpaf/utilities.git
  license: MIT License
  summary: "IOOS/SECOORA `utilities.py` module."
