package:
    name: utilities
    version: "0.2.6"

source:
    git_url: https://github.com/pyoceans/utilities.git
    git_tag: v0.2.6

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - iris
        - lxml
        - tardis
        - oceans
        - pandas
        - folium
        - owslib
        - pyugrid
        - requests
        - beautifulsoup4
        - ipython-notebook

test:
    imports:
        - utilities

about:
    home: https://github.com/pyoceans/utilities.git
    license: MIT License
    summary: "IOOS/SECOORA 'utilities.py' module"
