package:
    name: utilities
    version: "0.3.0"

source:
    git_url: https://github.com/pyoceans/utilities.git
    git_tag: v0.3.0

build:
    number: 1

requirements:
    build:
        - python <3
        - setuptools
    run:
        - python <3
        - iris  # [not py3k]
        - lxml
        - tardis  # [not py3k]
        - oceans
        - pandas
        - folium
        - owslib
        - pyugrid
        - requests
        - scikit-learn
        - beautifulsoup4
        - ipython-notebook

test:
    imports:
        - utilities

about:
    home: https://github.com/pyoceans/utilities.git
    license: MIT License
    summary: "IOOS/SECOORA 'utilities.py' module"
