{%set build = 2 %}
{%set version = "0.3.0" %}

package:
    name: utilities
    version: {{version}}

source:
    git_url: https://github.com/pyoceans/utilities.git
    git_tag: v{{version}}

build:
    number: {{build}}
    string: py{{py}}_{{build}}

requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python >=2.7,<3
        - iris  # [not py3k]
        - lxml
        - tardis  # [not py3k]
        - oceans
        - pandas
        - folium
        - owslib
        - pyugrid
        - requests
        - scikit-learn
        - beautifulsoup4
        - ipython-notebook

test:
    imports:
        - utilities

about:
    home: https://github.com/pyoceans/utilities.git
    license: MIT License
    summary: "IOOS/SECOORA 'utilities.py' module"
