package:
    name: oct2py
    version: "3.3.0"

source:
    fn: oct2py-3.3.0.tar.gz
    url: https://pypi.python.org/packages/source/o/oct2py/oct2py-3.3.0.tar.gz
    md5: b5bf35af92352e7463d01a37d812192c

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython

test:
    imports:
        - oct2py
        - oct2py.tests
        - oct2py.ipython
        - oct2py.ipython.tests

about:
    home: http://github.com/blink1073/oct2py
    license: MIT License
    summary: 'Python to GNU Octave bridge --> run m-files from python'
