package:
    name: oct2py
    version: "3.3.3"

source:
    fn: oct2py-3.3.3.zip
    url: https://pypi.python.org/packages/source/o/oct2py/oct2py-3.3.3.zip
    md5: 3490c75455f2968b0da90a6e07d1b9a0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython

test:
    imports:
        - oct2py
        - oct2py.tests
        - oct2py.ipython
        - oct2py.ipython.tests

about:
    home: http://github.com/blink1073/oct2py
    license: MIT License
    summary: 'Python to GNU Octave bridge --> run m-files from python'
