package:
    name: gridgen
    version: "1.48"

source:
    #git_url: https://github.com/phobson/gridgen.git
    #git_tag: v1.48
    git_url: https://github.com/ocefpaf/gridgen.git
    git_tag: make_file

build:
    number: 3

requirements:
    build:
        - gridutils
    run:
        - gridutils

about:
    home: https://code.google.com/p/gridgen-c
    license: MIT License
    summary: "Pavel Sakov's curvilinear orthogonal grid generation library"
