package:
    name: cligj
    version: "0.2.0"

source:
    fn: cligj-0.2.0.tar.gz
    url: https://pypi.python.org/packages/source/c/cligj/cligj-0.2.0.tar.gz
    md5: 2016c3d83d198a6840924b04a3962f3e

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - click
    run:
        - python
        - click

test:
    imports:
        - cligj

about:
    home: https://github.com/mapbox/cligj
    license: MIT
    summary: 'Click params for GeoJSON CLI'
