package:
    name: geopandas
    version: "0.1.1"

source:
    fn: geopandas-0.1.1.tar.gz
    url: https://pypi.python.org/packages/source/g/geopandas/geopandas-0.1.1.tar.gz
    md5: a01b5d3eb6bc097665a0ba297c39029f

build:
    skip: True  # [py35 and osx]
    skip: True  # [py35 and win]
    number: 1

requirements:
    build:
        - python
        - setuptools
        - cython >=0.16
    run:
        - python
        - pandas
        - pyproj >=1.9.3
        - shapely >=1.2.18
        - fiona >=1.0.1
        - six >=1.3.0
        - rtree >=0.8
        - descartes >=1.0
        - matplotlib >=1.2.1
        - psycopg2 >=2.5.1  # [not py3k and not win]
        - sqlalchemy >=0.8.3
        - geopy ==1.10.0
        - pysal  # [not py3k]

test:
    imports:
        - geopandas
        - geopandas.io

about:
    home: http://geopandas.org
    license: BSD
    summary: 'Geographic pandas extensions'
