package:
    name: mplleaflet
    version: "0.0.4"

source:
    fn: mplleaflet-0.0.4.tar.gz
    url: https://pypi.python.org/packages/source/m/mplleaflet/mplleaflet-0.0.4.tar.gz
    md5: 473b344b97ffa55b1724e53a148062b5

build:
    number: 0


requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - mplexporter

test:
    imports:
        - mplleaflet

about:
    home: https://github.com/jwass/mplleaflet
    license: BSD 3-clause
    summary: 'Convert Matplotlib plots into Leaflet web maps'
