package:
    name: mplleaflet
    version: "0.0.2"

source:
    fn: mplleaflet-0.0.2.tar.gz
    url: https://pypi.python.org/packages/source/m/mplleaflet/mplleaflet-0.0.2.tar.gz
    md5: 09222165aa81325e1561120709f12e4f

build:
    number: 0


requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - mplexporter

test:
    imports:
        - mplleaflet

about:
    home: https://github.com/jwass/mplleaflet
    license: BSD 3-clause
    summary: 'Convert Matplotlib plots into Leaflet web maps'
