package:
    name: mplleaflet
    version: "0.0.1"

source:
    fn: mplleaflet-0.0.1.tar.gz
    url: https://pypi.python.org/packages/source/m/mplleaflet/mplleaflet-0.0.1.tar.gz
    md5: 5911765b46b9e6d339ad8b9917b84c7e

build:
    number: 1


requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jinja2
        - mplexporter

test:
    imports:
        - mplleaflet

about:
    home: https://github.com/jwass/mplleaflet
    license: BSD 3-clause
    summary: 'Convert Matplotlib plots into Leaflet web maps'
