package:
    name: uncertainties
    version: "2.4.6.1"

source:
    fn: uncertainties-2.4.6.1.tar.gz
    url: https://pypi.python.org/packages/source/u/uncertainties/uncertainties-2.4.6.1.tar.gz
    md5: a30c01fda82b07ceb758e47e4768843f

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - uncertainties
        - uncertainties.lib1to2
        - uncertainties.lib1to2.fixes
        - uncertainties.unumpy
    requires:
        - nose
        - numpy

about:
    home: http://pythonhosted.org/uncertainties/
    license: BSD License
    summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives'
