package:
  name: iris
  version: !!str 1.7.2_DEV_9e1fd13

source:
  git_url: https://github.com/rhattersley/iris.git
  git_tag: lazy-dtype

build:
  number: 1

requirements:
  build:
    - python
    - scipy
    - biggus
    - cartopy >=0.11
    - netcdf4
    - udunits2
    - pyke
    - setuptools
    - libmo_unpack  # [not win]

  run:
    - python
    - scipy
    - biggus
    - cartopy >=0.11
    - matplotlib
    - netcdf4
    - ecmwf_grib >=1.12.1  # [not win]
    - numpy
    - pyke
    - udunits2
    - libmo_unpack  # [not win]

test:
  imports:
        - iris
        # FIXME: This is not working yet!
        #- iris.fileformats.pp_packing  # [not win]

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: "Analyse and visualise meteorological and oceanographic data sets."
