package:
  name: cartopy
  version: 0.11.1
source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.11.1

build:
  number: 0

requirements:
  build:
    - python
    - six
    - numpy
    - cython 
    - proj4 
    - shapely
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy 
    - proj4 
    - shapely
    - scipy   
    - pyshp  
    - matplotlib

test:
  imports:
    - cartopy

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
