{%set build = 0 %}
{%set version = "1.10.3" %}

package:
    name: pycsw
    version: {{version}}

source:
    git_url: https://github.com/geopython/pycsw.git
    git_tag: {{version}}

build:
    number: {{build}}
    string: py{{py}}_{{build}}
    preserve_egg_dir: True

requirements:
    build:
        - python >=2.7,<3
    run:
        - python >=2.7,<3
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

about:
    home: https://github.com/geopython/pycsw
    license: MIT
    summary: 'OGC Catalog Service for the Web (CSW) implementation in python'
