package:
    name: pycsw
    version: "1.10.2"

source:
    git_url: https://github.com/geopython/pycsw.git
    git_tag: 1.10.2
build:
    number: 1
    preserve_egg_dir: True

requirements:
    build:
        - python <3
        - setuptools
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely
    run:
        - python <3
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

about:
    home: https://github.com/geopython/pycsw
    license: MIT
    summary: 'OGC Catalog Service for the Web (CSW) implementation in python'
