package:
    name: pycsw
    version: "1.10.1"

source:
    git_url: https://github.com/geopython/pycsw.git

build:
    number: 2
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely
    run:
        - python
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

about:
    home: https://github.com/geopython/pycsw
    license: MIT
    summary: 'OGC Catalog Service for the Web (CSW) implementation in python'
