package:
    name: pyhum
    version: "1.3.2"

source:
    fn: PyHum-1.3.2.tar.gz
    url: https://pypi.python.org/packages/source/P/PyHum/PyHum-1.3.2.tar.gz
    md5: 8eb816f99e86bdc11eede7491628ea71

build:
    number: 0

requirements:
    build:
        - python
        - cython
        - numpy
    run:
        - python
        - numpy
        - scipy
        - pillow
        - matplotlib
        - scikit-learn
        - scikit-image
        - pyproj
        - joblib
        - simplekml
        - basemap
        - pyresample

test:
    imports:
        - PyHum

about:
    home: https://github.com/dbuscombe-usgs/PyHum
    license: GNU Library or Lesser General Public License (LGPL)
    summary: 'Python/Cython scripts to read Humminbird DAT'
