package:
    name: pyhum
    version: "1.3.0"

source:
    fn: PyHum-1.3.0.tar.gz
    url: https://pypi.python.org/packages/source/P/PyHum/PyHum-1.3.0.tar.gz
    md5: a6192050e6a7f74da038fd3c7123c5dd
    
build:
    number: 0

requirements:
    build:
        - python
        - cython
        - numpy
    run:
        - python
        - numpy
        - scipy
        - pillow
        - matplotlib
        - scikit-learn
        - pyproj
        - joblib
        - simplekml
        - basemap

test:
    imports:
        - PyHum

about:
    home: https://github.com/dbuscombe-usgs/PyHum
    license: GNU Library or Lesser General Public License (LGPL)
    summary: 'Python/Cython scripts to read Humminbird DAT'
