package:
  name: cartopy
  version: 0.10.0
source:
  git_url: git@github.com:SciTools/cartopy.git
  git_tag: v0.10.0

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython 
    - proj4 
    - shapely 1.3.0
  run:
    - python
    - pil
    - numpy
    - proj4 
    - shapely 1.3.0
    - scipy 0.13.2   
    - pyshp  
    - matplotlib 1.3.0

test:
  imports:
    - cartopy

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
