package:
  name: iris
  version: !!str v1.6.2_RPS
source:
  git_url: https://github.com/rsignell-usgs/iris.git

build:
  number: 0

requirements:
  build:
    - python
    - biggus
    - numpy
    - scipy 
    - udunits2
    - netcdf4 
    - pyke
    - cartopy   
    - geos
    - nose
    - setuptools
  run:
    - python
    - biggus
    - numpy
    - scipy 
    - udunits2
    - netcdf4 
    - geos
    - pyke
    - cartopy   
    - shapely
    - matplotlib

test:
  imports:

about:
  home: http://scitools.org.uk/iris
  license: Open Government License (UK)
