package:
  name: folium
  version: !!str 0.1.2

source:
  fn: folium-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/f/folium/folium-0.1.2.tar.gz
  md5: fabdbb84fc72f95bafb4154077588082
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - folium = folium:main
    #
    # Would create an entry point called folium that calls folium.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - jinja2

test:
  # Python imports
  imports:
    - folium

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wrobstory/folium
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

