package:
    name: octant
    version: "0.8.dev"

source:
    git_url: https://github.com/hetland/octant.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python <3
        - numpy
        - setuptools
        - mingwpy  # [win]
    run:
        - python
        - numpy
        - netcdf4
        - matplotlib
        - basemap

test:
    imports:
        - octant

about:
    home: https://github.com/hetland/octant
    license:  MIT
    summary: 'Ocean C-grid model setup and analysis tools, for the numerical mariner.'
