{%set build = 2 %}
{%set version = "0.8.dev" %}

package:
    name: octant
    version: {{version}}

source:
    git_url: https://github.com/hetland/octant.git
    git_tag: master

build:
    number: {{build}}
    string: py{{py}}_{{build}}

requirements:
    build:
        - python >=2.7,<3
        - numpy
        - setuptools
        - mingwpy  # [win]
    run:
        - python >=2.7,<3
        - numpy
        - netcdf4
        - matplotlib
        - basemap

test:
    imports:
        - octant

about:
    home: https://github.com/hetland/octant
    license:  MIT
    summary: 'Ocean C-grid model setup and analysis tools, for the numerical mariner.'
