package:
    name: seawater
    version: "3.3.3"

source:
    fn: seawater-3.3.3.tar.gz
    url: https://pypi.python.org/packages/source/s/seawater/seawater-3.3.3.tar.gz
    md5: ae3f13a9c406bafd225fba1acd73d56c

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    imports:
        - seawater

about:
    home: http://pypi.python.org/pypi/seawater/
    license: MIT License
    summary: 'Seawater Library for Python'
