package:
    name: cartopy
    version: 0.13.0

source:
    git_url: https://github.com/SciTools/cartopy.git
    git_tag: v0.13.0

    patches:
        - cartopy.win.patch  # [win]

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - six
        - numpy >=1.8,<1.10
        - cython
        - proj4 ==4.9.1  # [win]
        - proj4  # [not win]
        - geos
        # On OSX we need to effectively pin the geos version to the
        # one used by the specific shapely being targeted (we're letting
        # conda's package solver will deal with that).
        - shapely >=1.5.9
        - owslib
        - pyshp
        - pyepsg
    run:
        - python
        - six
        - mock
        - nose
        - pillow
        - owslib
        - numpy >=1.8,<1.10
        - proj4 ==4.9.1  # [win]
        - proj4  # [not win]
        - geos
        - shapely >=1.5.9
        - scipy
        - pyshp
        - matplotlib
        - pyepsg

test:
    imports:
        - cartopy
        - cartopy.mpl.geoaxes
        - cartopy.crs

about:
    home: http://scitools.org.uk/cartopy
    license: GNU LGPL
    summary: 'A library providing cartographic tools for python'
