package:
  name: munch
  version: 2.0.4

source:
  git_url: https://github.com/Infinidat/munch.git
  git_tag: 2.0.4

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - munch

about:
  home: https://github.com/Infinidat/munch
  license: https://github.com/Infinidat/munch/blob/master/LICENSE.txt
  summary: A Munch is a Python dictionary that provides attribute-style access (a la JavaScript objects).
