{%set build = 2 %}
{%set version = "1.1.1" %}

package:
    name: compliance-checker
    version: {{version}}

source:
    git_url: https://github.com/ioos/compliance-checker.git
    git_tag: {{version}}

build:
    number: {{build}}
    string: py{{py}}_{{build}}
    entry_points:
        - compliance-checker = cchecker:main

requirements:
    build:
        - python >=2.7,<3
        - setuptools
        - owslib
        - wicken
        - lxml
        - cf_units
        - requests
        - python-dateutil
    run:
        - python >=2.7,<3
        - owslib
        - wicken
        - lxml
        - cf_units
        - requests
        - python-dateutil

test:
    imports:
        - compliance_checker
        - compliance_checker.cf
        - compliance_checker.tests
    commands:
        - compliance-checker --help

about:
    home: https://github.com/ioos/compliance-checker
    license:  Apache Software License
    summary: 'Checks Datasets and SOS endpoints for standards compliance'
