package:
  name: compliance-checker
  version: !!str 1.0.0

source:
  fn: compliance-checker-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/c/compliance-checker/compliance-checker-1.0.0.tar.gz
  md5: 2f90064f9264cab60fee319a45ac652f

build:
  entry_points:
    - compliance-checker = cchecker:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - owslib >=0.8.3
    - wicken >=0.1.2
    - lxml >=3.2.1
    - udunitspy ==0.0.6
    - requests >=2.2.1
    - python-dateutil >=2.2
  run:
    - python
    - owslib >=0.8.3
    - wicken >=0.1.2
    - lxml >=3.2.1
    - udunitspy ==0.0.6
    - requests >=2.2.1
    - python-dateutil >=2.2

test:
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests

  commands:
    - compliance-checker --help

about:
  home: https://github.com/ioos/compliance-checker
  license:  Apache Software License
  summary: 'Checks Datasets and SOS endpoints for standards compliance'
