package:
    name: obvious-ci
    version: '0.3.x.dev'

source:
    git_url: https://github.com/pelson/Obvious-CI.git
    git_tag: master

build:
    number: 3

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - conda-server
        - conda
        - conda-build

about:
    home: https://github.com/pelson/Obvious-CI
    license: GPL
    summary: 'Simplify the implementation of continuous integration such as Travis CI and appveyor'
