package:
    name: django-debug-toolbar
    version: "1.3.0"

source:
    fn: django-debug-toolbar-1.3.0.tar.gz
    url: https://pypi.python.org/packages/source/d/django-debug-toolbar/django-debug-toolbar-1.3.0.tar.gz
    md5: a43c3232545e596fc5947b6454109874

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - django >=1.4.2
        - sqlparse
    run:
        - python
        - django >=1.4.2
        - sqlparse

#test:
    #imports:
        #- debug_toolbar
        #- debug_toolbar.management
        #- debug_toolbar.management.commands
        #- debug_toolbar.panels
        #- debug_toolbar.panels.sql
        #- debug_toolbar.panels.templates

about:
    home: https://github.com/django-debug-toolbar/django-debug-toolbar
    license: BSD License
    summary: 'A configurable set of panels that display various debug information about the current request/response.'
