package:
    name: django-extensions
    version: "1.5.7"

source:
    fn: django-extensions-1.5.7.tar.gz
    url: https://pypi.python.org/packages/source/d/django-extensions/django-extensions-1.5.7.tar.gz
    md5: 848bd98759ea32cf58f4977cd41e7cad

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT License
    summary: 'Extensions for Django'
