package:
    name: django-extensions
    version: "1.6.0"

source:
    fn: django-extensions-1.6.0.tar.gz
    url: https://pypi.python.org/packages/source/d/django-extensions/django-extensions-1.6.0.tar.gz
    md5: 081d8906aac8347e21b23ec5f8b4a315

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT License
    summary: 'Extensions for Django'
