package:
    name: django-extensions
    version: "1.5.9"

source:
    fn: django-extensions-1.5.9.tar.gz
    url: https://pypi.python.org/packages/source/d/django-extensions/django-extensions-1.5.9.tar.gz
    md5: f36493496ca4b10a3de4959db07e2d8e

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT License
    summary: 'Extensions for Django'
