package:
    name: django-extensions
    version: "1.5.5"

source:
    fn: django-extensions-1.5.5.tar.gz
    url: https://pypi.python.org/packages/source/d/django-extensions/django-extensions-1.5.5.tar.gz
    md5: 2c0b90a474ddb75764573f97a1481b82

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7,<1.8

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT License
    summary: 'Extensions for Django'
