package:
    name: geopy
    version: "1.10.0"

source:
    fn: geopy-1.10.0.tar.gz
    url: https://pypi.python.org/packages/source/g/geopy/geopy-1.10.0.tar.gz
    md5: 57cab8fd885a88ad4acecc53346e4c39

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - geopy
        - geopy.geocoders
    requires:
        - mock
        - pylint
        #- nose-cov
        #- tox

about:
    home: https://github.com/geopy/geopy
    license: MIT License
    summary: 'Python Geocoding Toolbox'
