package:
    name: ocgis
    version: 1.2.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: next

build:
    number: 0
    skip: True # [win and py3k]

requirements:
    build:
        - python >=2.7,<3
        - numpy
        - netcdf4
        - shapely
        - fiona ==1.6.2.dev1
        - cfunits-python
        - rtree
    run:
        - python >=2.7,<3
        - numpy
        - netcdf4
        - shapely
        - fiona ==1.6.2.dev1
        - proj.4
        - cfunits-python
        - rtree

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.