package:
    name: sparqlwrapper
    version: "1.7.5"

source:
    fn: SPARQLWrapper-1.7.5.tar.gz
    url: https://pypi.python.org/packages/source/S/SPARQLWrapper/SPARQLWrapper-1.7.5.tar.gz
    md5: a7c0cf069c7b2185e8bf265d49c705a0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - rdflib >=2.4.2
    run:
        - python
        - rdflib >=2.4.2
        - keepalive

test:
    imports:
        - SPARQLWrapper

about:
    home: http://sparql-wrapper.sourceforge.net/
    license: W3C License
    summary: 'SPARQL Endpoint interface to Python'
