package:
  name: sparqlwrapper
  version: !!str 1.6.0

source:
  fn: SPARQLWrapper-1.6.0.tar.gz
  url: https://pypi.python.org/packages/source/S/SPARQLWrapper/SPARQLWrapper-1.6.0.tar.gz
  md5: 5d9e0ce0949e17eab949ae82f3fcad4d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sparqlwrapper = sparqlwrapper:main
    #
    # Would create an entry point called sparqlwrapper that calls sparqlwrapper.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - rdflib >=2.4.2

  run:
    - python
    - rdflib >=2.4.2

test:
  # Python imports
  imports:
    - SPARQLWrapper
    - sparqlwrapper

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sparql-wrapper.sourceforge.net/
  license: W3C License
  summary: 'SPARQL Endpoint interface to Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
