package:
    name: sparqlwrapper
    version: "1.7.4"

source:
    fn: SPARQLWrapper-1.7.4.tar.gz
    url: https://pypi.python.org/packages/source/S/SPARQLWrapper/SPARQLWrapper-1.7.4.tar.gz
    md5: a235432b2bbf738acde8122f2fd3625e

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - rdflib >=2.4.2
    run:
        - python
        - rdflib >=2.4.2
        - keepalive

test:
    imports:
        - SPARQLWrapper

about:
    home: http://sparql-wrapper.sourceforge.net/
    license: W3C License
    summary: 'SPARQL Endpoint interface to Python'
