package:
  name: pyugrid
  version: !!str 0.1.1

source:
  git_url: https://github.com/pyugrid/pyugrid.git

build:
  number: 0

requirements:
  build:
    - python
    - netcdf4
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - netcdf4

test:
  # Python imports
  imports:
    - pyugrid

about:
  home: http://github.com/pyugrid/pygrid.git
  license: 'BSD'
  summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions.'
