package:
    name: pyugrid
    version: "0.1.6"

source:
    fn: pyugrid-0.1.6.tar.gz
    url: https://pypi.python.org/packages/source/p/pyugrid/pyugrid-0.1.6.tar.gz
    md5: cb1c1196fefa44fae555659aeb91b7ee

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
