package:
  name: click-plugins
  version: 1.0.2

source:
  git_url: https://github.com/click-contrib/click-plugins.git
  git_tag: 1.0.2

build:
  number: 1

requirements:
  build:
    - python
    - click >=3.0

  run:
    - python
    - click >=3.0

about:
  home: https://github.com/click-contrib/click-plugins
  license: New BSD License
  summary: Register CLI commands via setuptools entry-points.
