package:
    name: thredds_crawler
    version: "1.1.0"

source:
    fn: thredds_crawler-1.1.0.tar.gz
    url: https://pypi.python.org/packages/source/t/thredds_crawler/thredds_crawler-1.1.0.tar.gz
    md5: 81e499f791c7bcc8a01f95f94db01fef

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - requests
        - lxml
    run:
        - python
        - requests
        - lxml
        - netcdf4

test:
    imports:
        - tests
        - thredds_crawler

about:
    home: https://github.com/asascience-open/thredds_crawler
    license:  GNU General Public License v3 (GPLv3)
    summary: 'A Python library for crawling THREDDS servers'
