package:
    name: sci-wms
    version: "1.1.0"

build:
    number: 0

requirements:
    run:
        - python
        # requirements.txt
        - numpy
        - django >=1.7,<1.8
        - python-dateutil
        - matplotlib >=1.2.0
        - netcdf4 >=1.0.2
        - rtree 0.7.0
        - jsonfield
        - pytz
        - djangorestframework
        - pyugrid
        - pysgrid
        - pyaxiom
        - django-grappelli
        - django-typed-models
        - pyproj
        - dj-static
        - pandas
        - django-autoslug
        # requirements-prod.txt
        - gunicorn >=0.13.4
        - setproctitle  # [not win]
        - tornado
        # requirements-dev.txt
        - django-extensions
        - werkzeug
        - watchdog
        - django-debug-toolbar

about:
    home: https://github.com/sci-wms/sci-wms
    license: GNU General Public License v3 (GPLv3)
    summary: 'A Python WMS service for geospatial gridded data'
