package:
  name: sci-wms
  version: !!str 0.1.0 
source:
# using Kyle Wilcox forked stable branch for now
# as the origin is not currently stable
  git_url: https://github.com/kwilcox/sci-wms.git
  git_tag: stable
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sci-wms = sci-wms:main
    #
    # Would create an entry point called sci-wms that calls sci-wms.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.

requirements:
  build:

  run:
    - python
    - django
    - shapely
    - numpy
    - greenlet
    - gevent
    - gunicorn
    - python-dateutil
    - matplotlib
    - netcdf4
    - rtree 0.7*
    - south
    - basemap
    - jsonfield

test:
  # Python imports
  imports:
#   - tests
#   - sci-wms
#   - tests.collectors

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/asa-science-open.github.io/sci-wms
  license: GNU General Public License v3 (GPLv3)
  summary: 'A Python WMS service for geospatial grid and mesh data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
