package:
    name: sci-wms
    version: "0.0.2"

build:
    number: 0

build:
    number: 2

requirements:
    run:
        - python
        # requirements.txt
        - numpy
        - django >=1.7,<1.8
        - shapely
        - python-dateutil
        - matplotlib >=1.2.0
        - netcdf4 >=1.0.2
        - rtree 0.7.0
        - south
        - jsonfield
        - pytz
        - djangorestframework
        - pyugrid
        - basemap
        # requirements-prod.txt
        - gunicorn >=0.13.4
        - setproctitle  # [not win]
        - tornado
        # requirements-dev.txt
        - django-extensions
        - werkzeug


about:
    home: https://github.com/sci-wms/sci-wms
    license: GNU General Public License v3 (GPLv3)
    summary: 'A Python WMS service for geospatial gridded data'
