{%set build = 3 %}
{%set version = "2.0.1" %}

package:
    name: pygdp
    version: {{version}}

source:
    git_url: https://github.com/USGS-CIDA/pyGDP.git
    git_tag: v{{version}}

build:
    number: {{build}}
    string: py{{py}}_{{build}}

requirements:
    build:
        - python >=2.7,<3
        - setuptools
        - owslib
    run:
        - python >=2.7,<3
        - owslib
        - python-dateutil
        - lxml
test:
    imports:
        - pyGDP

about:
    home: https://github.com/USGS-CIDA/pyGDP
    license: CC0
    summary: 'python interface to facilitate working with USGS-CIDA Geo Data Portal web services'
