package:
  name: pygdp
  version: !!str 1.2.2

source:
  git_url: https://github.com/USGS-CIDA/pyGDP.git
  git_tag: v1.2.2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygdp = pygdp:main
    #
    # Would create an entry point called pygdp that calls pygdp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.

requirements:
  build:
    - python
    - setuptools
    - owslib
  run:
    - python
    - owslib

test:
  # Python imports
  imports:
    - pyGDP

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: CC0
  summary: 'python interface to facilitate working with USGS-CIDA Geo Data Portal web services'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
