package:
    name: pygdp
    version: "1.3.2"

source:
    git_url: https://github.com/USGS-CIDA/pyGDP.git
    git_tag: v1.3.2

build:
    number: 2

requirements:
    build:
        - python <3
        - setuptools
        - owslib
    run:
        - python <3
        - owslib
        - python-dateutil
        - lxml
test:
    imports:
        - pyGDP

about:
    home: https://github.com/USGS-CIDA/pyGDP
    license: CC0
    summary: 'python interface to facilitate working with USGS-CIDA Geo Data Portal web services'
