package:
  name: jsanimation
  version: !!str 0.1
source:
  git_url: https://github.com/jakevdp/JSAnimation.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:

about:
  home: http://github.com/jakevdp
  license: BSD
