package:
    name: djangorestframework
    version: "3.1.3"

source:
    fn: djangorestframework-3.1.3.tar.gz
    url: https://pypi.python.org/packages/source/d/djangorestframework/djangorestframework-3.1.3.tar.gz
    md5: 51dcf19a33c99975b3e3ff6e8af93975

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - rest_framework
        - rest_framework.authtoken
        - rest_framework.authtoken.migrations
        - rest_framework.authtoken.south_migrations
        - rest_framework.templatetags
        - rest_framework.utils

about:
    home: http://www.django-rest-framework.org
    license: BSD License
    summary: 'Web APIs for Django, made easy'
