package:
  name: iris
  version: !!str 1.6.2_DEV
source:
  git_url: https://github.com/SciTools/iris.git

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy 0.13.2
    - udunits2
    - netcdf4 1.0.6
    - pyke
    - cartopy   
    - nose
    - setuptools
  run:
    - python
    - numpy
    - scipy 0.13.2  
    - udunits2
    - netcdf4 1.0.6
    - pyke
    - cartopy   
    - shapely
    - matplotlib

test:
  imports:

about:
  home: http://scitools.org.uk/iris
  license: Open Government License (UK)
