package:
    name: pyaxiom
    version: "1.1.4"

source:
    fn: pyaxiom-1.1.4.tar.gz
    url: https://pypi.python.org/packages/source/p/pyaxiom/pyaxiom-1.1.4.tar.gz
    md5: 5bff6763325715fb3300cb2bb4df7274

build:
    number: 0
    entry_points:
        - binner=pyaxiom.netcdf.grids.binner:run

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pytz
        - python-dateutil
        - netcdf4
        - pandas
        - pyncml
        - pynco  # [not win]

test:
    imports:
        - pyaxiom
        - pyaxiom.netcdf
        - pyaxiom.netcdf.grids
        - pyaxiom.netcdf.sensors
        - pyaxiom.tests
    commands:
        - binner --help

about:
    home: https://github.com/axiom-data-science/pyaxiom
    license: MIT License
    summary: 'An ocean data toolkit developed and used by Axiom Data Science'
