package:
    name: beautifulsoup4
    version: "4.4.0"

source:
    fn: beautifulsoup4-4.4.0.tar.gz
    url: https://pypi.python.org/packages/source/b/beautifulsoup4/beautifulsoup4-4.4.0.tar.gz
    md5: 63d1f33e6524f408cb6efbc5da1ae8a5

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - lxml
        - html5lib

test:
    imports:
        - bs4
        - bs4.builder
        - bs4.tests

about:
    home: http://www.crummy.com/software/BeautifulSoup/bs4/
    license: MIT License
    summary: 'Beautiful Soup sits atop an HTML or XML parser, providing Pythonic idioms for iterating, searching, and modifying the parse tree'
