package:
  name: udunits2
  version: 2.2.16
source:
  fn:  udunits-2.2.16.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.16.tar.gz

build:
  number: 0

requirements:
  build:

  run:

test:
  imports:

  commands:

about:
  home: http://www.unidata.ucar.edu
  license: MIT
  summary: 'A library for manipulating units of physical quantities.'
