{%set build = 2 %}
{%set version = "0.1.1" %}

package:
    name: tardis
    version: {{version}}

source:
    git_url: https://github.com/pyoceans/tardis.git
    git_tag: v{{version}}

build:
    number: {{build}}
    string: py{{py}}_{{build}}

requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python >=2.7,<3
        - iris
        - pytz
        - numpy
        - scipy
        - oceans
        - pyugrid

test:
    imports:
        - tardis

about:
    home: https://github.com/pyoceans/tardis.git
    license: MIT License
    summary: "TARDIS is a collection of functions for SciTools Iris"
