package:
  name: south
  version: "1.0.1"

source:
  fn: South-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/S/South/South-1.0.1.tar.gz
  md5: 9977423e4c4f7ca9345f1428a0a57505
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - south = south:main
    #
    # Would create an entry point called south that calls south.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - south

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://south.aeracode.org/
  license: ache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
