package:
    name: colander
    version: !!str 1.0

source:
    fn: colander-1.0.tar.gz
    url: https://pypi.python.org/packages/source/c/colander/colander-1.0.tar.gz
    md5: 058576123da7216288c079c9f47693f8

requirements:
    build:
        - python
        - setuptools
        - translationstring

    run:
        - python
        - translationstring

test:
    imports:
        - colander
        - colander.tests

about:
    home: http://docs.pylonsproject.org/projects/colander/en/latest/
    license: BSD-derived (http://www.repoze.org/LICENSE.txt)
    summary: 'A simple schema-based serialization and deserialization library'
