package:
  name: pytest-cov
  version: !!str 1.7.0

source:
  fn: pytest-cov-1.7.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest-cov/pytest-cov-1.7.0.tar.gz
  md5: c1432814f2e19ed86b563efa374b23a1

build:
 number: 0

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.5.2
    - cov-core >=1.12

  run:
    - python
    - pytest >=2.5.2
    - cov-core >=1.12

about:
  home: https://github.com/schlamar/pytest-cov
  license:  MIT License
  summary: 'py.test plugin for coverage reporting with support for both centralised and distributed testing, including subprocesses and multiprocessing'
