package:
    name: owslib
    version: "0.9.1"

source:
    git_url: https://github.com/geopython/OWSLib.git
    git_tag: 0.9.1

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - python-dateutil
        - pytz
        - requests
        - lxml
        - pyproj

test:
    imports:
        - owslib.coverage
        - owslib.waterml
        - owslib.swe.observation
        - owslib.swe.sensor
        - owslib
        - owslib.feature
        - owslib.swe

about:
    home: https://geopython.github.io/OWSLib
    license: BSD License
    summary: 'OGC Web Service utility library'
