package:
    name: regex
    version: "2015.10.05"

source:
    fn: regex-2015.10.05.tar.gz
    url: https://pypi.python.org/packages/source/r/regex/regex-2015.10.05.tar.gz
    md5: e188645a76d82d7b1cb0c12989665b8e

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://code.google.com/p/mrab-regex-hg/
    license: Python Software Foundation License
    summary: 'Alternative regular expression module, to replace re.'
