package:
    name: regex
    version: "2015.09.23"

source:
    fn: regex-2015.09.23.tar.gz
    url: https://pypi.python.org/packages/source/r/regex/regex-2015.09.23.tar.gz
    md5: dc00d72a99840451e782c7b7a70ed50b

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://code.google.com/p/mrab-regex-hg/
    license: Python Software Foundation License
    summary: 'Alternative regular expression module, to replace re.'
