package:
    name: regex
    version: "2015.11.08"

source:
    fn: regex-2015.11.08.tar.gz
    url: https://pypi.python.org/packages/source/r/regex/regex-2015.11.08.tar.gz
    md5: 5aa5cde03445e5b1d2a1cf5950ce4941

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://code.google.com/p/mrab-regex-hg/
    license: Python Software Foundation License
    summary: 'Alternative regular expression module, to replace re.'
