package:
    name: boost
    version: "1.58.0"

source:
    fn:  boost_1_58_0.tar.bz2
    url: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2
    md5: b8839650e61e9c1c0a89f371dd475546

build:
    number: 0

about:
    home: http://www.boost.org
    license: BSL-1.0
    summary: 'Boost provides free portable peer-reviewed C++ libraries'
