{%set build = 2 %}
{%set version = "0.1.3" %}

package:
    name: petulant-bear
    version: {{version}}

source:
    fn: petulant-bear-0.1.3.tar.gz
    url: https://pypi.python.org/packages/source/p/petulant-bear/petulant-bear-0.1.3.tar.gz
    md5: 71788a47d6a9c7b0081ab81348c4f4a9

build:
    number: {{build}}
    string: py{{py}}_{{build}}


requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python >=2.7,<3
        - netcdf4
        - numpy
        - lxml

test:
    imports:
        - petulantbear

about:
    home: https://github.com/ioos/petulant-bear
    license:  GNU General Public License v3 (GPLv3)
    summary: 'Presents etree interface to netcdf4-python objects using NCML data model'
