package:
    name: django-grappelli
    version: "2.7.1"

source:
    fn: django-grappelli-2.7.1.tar.gz
    url: https://pypi.python.org/packages/source/d/django-grappelli/django-grappelli-2.7.1.tar.gz
    md5: 97a2d3380475ca792dea2c0edcb6a0ba

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django

test:
    imports:
        - grappelli
        #- grappelli.dashboard
        #- grappelli.dashboard.management
        #- grappelli.dashboard.management.commands
        #- grappelli.dashboard.templatetags
        - grappelli.templatetags
        - grappelli.tests
        - grappelli.views

about:
    home: http://django-grappelli.readthedocs.org
    license: BSD License
    summary: 'A jazzy skin for the Django Admin-Interface.'
