package:
    name: xray
    version: "0.6.0"

source:
    fn: xray-0.6.0.tar.gz
    url: https://pypi.python.org/packages/source/x/xray/xray-0.6.0.tar.gz
    md5: f6331054e509b92e7f87b0db1cb84954

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - netcdf4
        - scipy
        - bottleneck
        - dask
        - h5netcdf
        - cyordereddict

test:
    imports:
        - xray
        - xray.backends
        - xray.core
        - xray.test

about:
    home: https://github.com/xray/xray
    license: Apache Software License
    summary: 'N-D labeled arrays and datasets in Python'
