package:
    name: xray
    version: "0.6.1"

source:
    fn: xray-0.6.1.tar.gz
    url: https://pypi.python.org/packages/source/x/xray/xray-0.6.1.tar.gz
    md5: 7d5e0e3ba365017d7a8b6542c48c4ce6

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - netcdf4
        - scipy
        - bottleneck  # [not py35]
        - dask >=0.6
        - h5netcdf
        - cyordereddict

test:
    imports:
        - xray
        - xray.backends
        - xray.core
        - xray.test

about:
    home: https://github.com/xray/xray
    license: Apache Software License
    summary: 'N-D labeled arrays and datasets in Python'
