package:
    name: nco
    version: 4.5.0

source:
    fn: nco-4.5.0.tar.gz
    url: http://nco.sourceforge.net/src/nco-4.5.0.tar.gz
    md5: cc387b92e796a778bddefab79cda0a34

build:
    number: 0

requirements:
    build:
        - curl
        - zlib
        - libnetcdf
        - hdf5
        - udunits2
        #- gsl
        #- antlr
    run:
        - libnetcdf
        - udunits2

test:
    commands:
        - ncks --help
        - ncks -M http://test.opendap.org/dap/data/nc/sst.mnmean.nc.gz
        #- ncks http://thredds-test.ucar.edu/thredds/dodsC/testdods/in.nc in.nc
        #- ncap2 -v -s 'a=3' -s 'b=4' -s 'c=sqrt(a^2+b^2)' in.nc out.nc

about:
    home: http://nco.sourceforge.net/
    license: GPL-3.0
    summary: 'Suite of programs for manipulating NetCDF/HDF4 files'
