package:
    name: nco
    version: 4.5.1

source:
    fn: nco-4.5.1.tar.gz
    url: http://nco.sourceforge.net/src/nco-4.5.1.tar.gz
    md5: b830dd0a825335731a7c9ecd45c0a00f
    patches:
        - nodocs.patch  # [osx]

build:
    number: 0

requirements:
    build:
        - curl
        - zlib
        - hdf5
        - libnetcdf
        - udunits2
    run:
        - hdf5
        - libnetcdf
        - udunits2

test:
    commands:
        - ncks --help
        - ncks -M http://test.opendap.org/dap/data/nc/sst.mnmean.nc.gz
        - ncks -F --dimension time,1 http://test.opendap.org/dap/data/nc/sst.mnmean.nc.gz in.nc
        - ncap2 -v -s 'a=3' -s 'b=4' -s 'c=sqrt(a^2+b^2)' in.nc out.nc  # [not osx]

about:
    home: http://nco.sourceforge.net/
    license: GPL-3.0
    summary: 'Suite of programs for manipulating NetCDF/HDF4 files'
