package:
  name: epic2cf
  version: !!str 0.0.1

source:
  fn: epic2cf-0.0.1.tar.gz
  url: https://pypi.python.org/packages/source/e/epic2cf/epic2cf-0.0.1.tar.gz
  md5: 0b77a721a7dd46d51c70920be77cca29
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - epic2cf = epic2cf:main
    #
    # Would create an entry point called epic2cf that calls epic2cf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - epic2cf

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/axiom-data-science/epic2cf
  license: MIT License
  summary: 'A simple python library to find the CF standard name equivalent of an EPIC code.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
