package:
    name: proj4
    version: "4.9.1"

build:
    number: 2

source:
    fn:  proj-4.9.1.tar.gz
    url: http://download.osgeo.org/proj/proj-4.9.1.tar.gz

about:
    home: http://trac.osgeo.org/proj/
    license: MIT
    summary: 'Cartographic projection software'
