package:
    name: pykdtree
    version: "1.0"

source:
    fn: pykdtree-1.0.tar.gz
    url: https://pypi.python.org/packages/source/p/pykdtree/pykdtree-1.0.tar.gz
    md5: 71cae67da7f95e3242e1d05d3053361f
    patches:
        - win_comp.patch  # [win]

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy

test:
    imports:
        - pykdtree

about:
    home: https://pypi.python.org/pypi/pykdtree
    license: GNU General Public License v3 (GPLv3)
    summary: 'Fast kd-tree implementation with OpenMP-enabled queries'
