package:
    name: ulmo
    version: "0.8.1"

source:
    fn: ulmo-0.8.1.tar.gz
    url: https://pypi.python.org/packages/source/u/ulmo/ulmo-0.8.1.tar.gz
    md5: a628f6e031748e152c4a98194b96fec3

build:
    number: 0
    skip: True  # [py35 and win]

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - appdirs
        - beautifulsoup4
        - future
        - geojson
        - isodate
        - numpy
        - pandas
        - pytables # [not win and not py3k]
        - pytables <=3.1.1 # [win and py3k]
        - requests
        - suds-jurko
        - lxml
        - mock

test:
    imports:
        - ulmo.usgs.nwis
        - ulmo.cdec.historical
        - ulmo.util
        - ulmo.waterml
        - ulmo.ncdc
        - ulmo.cpc
        - ulmo.cuahsi
        - ulmo.cpc.drought
        - ulmo.ncdc.gsod
        - ulmo.usgs.eddn
        - ulmo.ncdc.cirs
        - ulmo.twc
        - ulmo.cuahsi.his_central
        - ulmo.usgs
        - ulmo.usace.rivergages
        - ulmo
        - ulmo.ncdc.ghcn_daily
        - ulmo.usace.swtwc
        - ulmo.twc.kbdi
        - ulmo.cuahsi.wof
        - ulmo.usace
        - ulmo.cdec
    requires:
        - pytest
        - freezegun
        - httpretty

about:
    home: https://github.com/ulmo-dev/ulmo/
    license: BSD License
    summary: 'Clean, simple and fast access to public hydrology and climatology data'
