package:
    name: pyscaffold
    version: "2.5.2"

source:
    fn: PyScaffold-2.5.2.tar.gz
    url: https://pypi.python.org/packages/source/P/PyScaffold/PyScaffold-2.5.2.tar.gz
    md5: 2f20f32208188393b96bc92fe97e03bd

build:
    number: 0
    skip: True  # [py35]
    preserve_egg_dir: True
    entry_points:
        - putup=pyscaffold.cli:run


requirements:
    build:
        - python
        - setuptools
        - setuptools_scm >=1.7
        - six
        - pbr >=1.6
    run:
        - python
        - six
        - pbr >=1.6

test:
    imports:
        - pyscaffold
        #- pyscaffold.contrib
        - pyscaffold.templates
    commands:
        - putup --help
    requires:
        - pytest
        - pytest-cov  # [not py3k]

about:
    home: http://pyscaffold.readthedocs.org/
    license: BSD License
    summary: 'Template tool for putting up the scaffold of a Python project'
