package:
    name: geojson
    version: "1.2.2"

source:
    fn: geojson-1.2.2.tar.gz
    url: https://pypi.python.org/packages/source/g/geojson/geojson-1.2.2.tar.gz
    md5: 8c039d712042c84352c7690aeff66d81

build:
    number: 0
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - geojson

about:
    home: https://github.com/frewsxcv/python-geojson
    license: BSD License
    summary: 'Python bindings and utilities for GeoJSON'
