package:
    name: geojson
    version: "1.3.0"

source:
    fn: geojson-1.3.0.tar.gz
    url: https://pypi.python.org/packages/source/g/geojson/geojson-1.3.0.tar.gz
    md5: 535cbfd4d2c98b40cebf91337711d2f0

build:
    number: 0
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - geojson

about:
    home: https://github.com/frewsxcv/python-geojson
    license: BSD License
    summary: 'Python bindings and utilities for GeoJSON'
