package:
    name: paegan
    version: "1.1.3"

source:
    fn: paegan-1.1.3.tar.gz
    url: https://pypi.python.org/packages/source/p/paegan/paegan-1.1.3.tar.gz
    md5: 6dbf789f63ddcfbe85857396ad6a8d18

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - netcdf4
        - shapely
        - pytz
        - python-dateutil

test:
    imports:
        - paegan
        - paegan.logger
        - paegan.roms
        - paegan.cdm.grids
        - paegan.cdm
        - paegan.external
        - paegan.cdm.dsg.collections.base
        - paegan.utils
        - paegan.cdm.dsg.features.base
        - paegan.cdm.dsg.features
        - paegan.cdm.dsg.collections
        - paegan.cdm.dsg

about:
    home: https://github.com/axiom-data-science/paegan
    license: GNU General Public License v3 (GPLv3)
    summary: 'Paegan - The Python CDM for Met/Ocean data'
