package:
    name: django-typed-models
    version: "0.4.0"

source:
    fn: django-typed-models-0.4.0.tar.gz
    url: https://pypi.python.org/packages/source/d/django-typed-models/django-typed-models-0.4.0.tar.gz
    md5: 47ad7f8eaf39f4551d2a35864bb7b445

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - django

#test:
    #imports:
        #- typedmodels

about:
    home: http://github.com/craigds/django-typed-models
    license: BSD License
    summary: 'Sane single table model inheritance for Django'
