{%set build = 2 %}
{%set version = "1.9.4" %}

package:
    name: pyproj
    version: {{version}}

source:
    fn: pyproj-1.9.4.tar.gz
    url: https://pypi.python.org/packages/source/p/pyproj/pyproj-1.9.4.tar.gz
    md5: b0a060465b117dd6c1b37e14f22382aa

build:
    number: {{build}}
    string: py{{py}}_{{build}}

requirements:
    build:
        - python >=2.7,<3
    run:
        - python >=2.7,<3
        - numpy

test:
    imports:
        - pyproj

about:
    home: https://github.com/jswhit/pyproj
    license: OSI
    summary: 'Python interface to PROJ.4 library'
