package:
    name: pyproj
    version: "1.9.4"

source:
    git_url: https://github.com/ocefpaf/pyproj.git
    git_tag: travis

build:
    number: 3

requirements:
    build:
        - python
    run:
        - python
        - numpy

test:
    imports:
        - pyproj

about:
    home: https://github.com/jswhit/pyproj
    license: OSI
    summary: 'Python interface to PROJ.4 library'
