package:
    name: csa
    version: "1.22.0"

source:
    git_url: https://github.com/sakov/csa-c.git
    git_tag: v1.22.0

build:
    number: 0

about:
    home: https://github.com/sakov/csa-c.git
    license: Simplified BSD
    summary: "Cubic Spline Approximation"
