package:
  name: shapely
  version: !!str 1.3.1

source:
  fn: Shapely-1.3.1.tar.gz
  url: https://pypi.python.org/packages/source/S/Shapely/Shapely-1.3.1.tar.gz
  md5: 5ac028637fbd52b9752994bdbfd9446c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - shapely = shapely:main
    #
    # Would create an entry point called shapely that calls shapely.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - geos

  run:
    - python
    - geos 
test:
  # Python imports
  imports:
    - shapely.tests
    - shapely.algorithms
    - shapely
    - shapely.geometry
    - shapely.examples
    - shapely.speedups

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
