package:
    name: nn
    version: 1.85

source:
    #git_url: https://github.com/phobson/nn.git
    #git_tag: v1.85
    git_url: https://github.com/ocefpaf/nn.git
    git_tag: points_generate2

build:
    number: 3

about:
    home: https://code.google.com/p/nn-c
    license: MIT License
    summary: "Pavel Sakov's natural neighbors library"
